language: python

python:
  - 2.7
  - 3.4

branches:
  only:
    - master

env:
  - CUDARRAY_BACKEND=numpy

install:
  # The following steps are copied from
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy cython pillow pytest scikit-learn
  - source activate test-environment

  - git clone https://github.com/andersbll/cudarray.git
  - cd cudarray && python setup.py --without-cuda develop && cd ..
  - python setup.py develop

script:
  - python setup.py test

notifications:
  irc:
    channels:
      - chat.freenode.net#deeppy
    on_success: always
    on_failure: always
